CREATE TABLE IF NOT EXISTS budget (
  id INTEGER PRIMARY KEY CHECK (id BETWEEN 1 AND 10),
  bytes INTEGER NOT NULL DEFAULT 0,
  day TEXT NOT NULL DEFAULT '',
  uploads INTEGER NOT NULL DEFAULT 0
);
INSERT OR IGNORE INTO budget (id) VALUES (1),(2),(3),(4),(5),(6),(7),(8),(9),(10);
